### PR TITLE
Allowing capitalized .set() options.

### PR DESCRIPTION
**Pull request by jpodwys**
This matches node_redis.

@vogonistic @sxyizhiren @wilkenstein

### CODE REVIEW

**Comment by jpodwys** [comment]
@wilkenstein any ETA on when you might be able to merge this? The changes are tiny.

**Comment by wilkenstein** [comment]
@jpodwys Done in 0.0.12-7 release

**Comment by jpodwys** [comment]
Thank you! I really appreciate this project, BTW.

**Comment by wilkenstein** [comment]
@jpodwys Aw, shucks :) glad it's helpful to you! I wish I had more time to spend with it lately, but c'est la vie.

**Comment by jpodwys** [comment]
Well, even without you being able to actively develop at the moment, it's still the most complete redis mock I've found.

**Pull request merged**
